

const MIN_MIDI_NOTE = 36;
const MAX_MIDI_NOTE = 83

const NUM_MIDI_CLASSES = MAX_MIDI_NOTE - MIN_MIDI_NOTE; // 48

const LOOP_DURATION = 32; // 2bars x 16th note

const ORIGINAL_DIM = NUM_MIDI_NOTES * LOOP_DURATION;

exports.MIN_MIDI_NOTE = MIN_MIDI_NOTE;
exports.MAX_MIDI_NOTE = MAX_MIDI_NOTE;
exports.NUM_MIDI_CLASSES = NUM_MIDI_CLASSES;

exports.LOOP_DURATION = LOOP_DURATION;
exports.ORIGINAL_DIM = ORIGINAL_DIM;